const londonCourses = [
  {
    name: "Beginner Ballet",
    duration: "12 weeks",
    type: "ballet",
    startDate: "2025-04-01",
    day: "Monday",
    startTime: "18:00",
    endTime: "20:00",
    description: "A ballet class for dancers at an beginner level",
    location: "London",
    level: 1,
    price: 150.0,
    participants: [
      {
        firstName: "Mervin",
        lastName: "Croney",
        email: "mcroney0@tuttocitta.it",
      },
      {
        firstName: "Odille",
        lastName: "Lawdham",
        email: "olawdham1@blogs.com",
      },
      {
        firstName: "Gerianne",
        lastName: "Tipping",
        email: "gtipping2@mac.com",
      },
      { firstName: "Kenton", lastName: "Quelch", email: "kquelch3@census.gov" },
    ],
  },
  {
    name: "Intermediate Ballet",
    type: "ballet",
    duration: "12 weeks",
    startDate: "2025-04-02",
    day: "Tuesday",
    startTime: "18:00",
    endTime: "20:00",
    description: "A ballet class for dancers at an intermediate level",
    location: "London",
    level: 2,
    price: 150.0,
    participants: [
      {
        firstName: "Ruthe",
        lastName: "Britton",
        email: "rbritton4@ycombinator.com",
      },
      {
        firstName: "Edwina",
        lastName: "Hubbold",
        email: "ehubbold5@diigo.com",
      },
    ],
  },
  {
    name: "Advanced Ballet",
    type: "ballet",
    duration: "12 weeks",
    startDate: "2025-04-03",
    day: "Wednesday",
    startTime: "18:00",
    endTime: "20:00",
    description: "A ballet class for dancers at an advanced level",
    location: "London",
    level: 3,
    price: 150.0,
    participants: [
      {
        firstName: "Murdock",
        lastName: "Samsonsen",
        email: "msamsonsen6@rakuten.co.jp",
      },
      {
        firstName: "Almeria",
        lastName: "Harrild",
        email: "aharrild7@marketwatch.com",
      },
      { firstName: "Camile", lastName: "Drewitt", email: "cdrewitt8@icio.us" },
    ],
  },
];

const glasgowCourses = [
  {
    name: "Beginner Hip Hop",
    type: "hip hop",
    duration: "12 weeks",
    startDate: "2025-04-03",
    day: "Saturday",
    startTime: "12:00",
    endTime: "14:00",
    description: "A ballet class for dancers at an beginner level",
    level: 1,
    location: "Glasgow",
    price: 125.0,
    participants: [
      {
        firstName: "Stephine",
        lastName: "Raittie",
        email: "sraittie9@sciencedirect.com",
      },
      {
        firstName: "Roxanna",
        lastName: "MacTrustie",
        email: "rmactrustiea@prnewswire.com",
      },
      {
        firstName: "Camile",
        lastName: "Allicock",
        email: "callicockb@house.gov",
      },
      {
        firstName: "Sholom",
        lastName: "Silber",
        email: "ssilberc@twitpic.com",
      },
      {
        firstName: "Wilhelm",
        lastName: "Brainsby",
        email: "wbrainsbyd@wufoo.com",
      },
      { firstName: "Kelwin", lastName: "Dollin", email: "kdolline@mysql.com" },
    ],
  },
  {
    name: "Intermediate Hip Hop",
    type: "hip hop",
    duration: "12 weeks",
    startDate: "2025-04-03",
    day: "Tuesday",
    startTime: "18:00",
    endTime: "20:00",
    description: "A tap dancing class for dancers at an intermediate level",
    location: "Glasgow",
    level: 2,
    price: 150.0,
    participants: [
      { firstName: "Terence", lastName: "Fysh", email: "tfyshf@yahoo.com" },
      { firstName: "Jami", lastName: "Dollar", email: "jdollarg@sogou.com" },
    ],
  },
  {
    name: "Advanced Hip Hop",
    type: "hip hop",
    duration: "12 weeks",
    startDate: "03-04-2025",
    day: "Wednesday",
    startTime: "18:00",
    endTime: "20:00",
    description: "A tap dancing class for dancers at an advanced level",
    location: "Glasgow",
    level: 3,
    price: 125.0,
    participants: [
      { firstName: "Kiley", lastName: "Bonas", email: "kbonash@eepurl.com" },
      { firstName: "Ursa", lastName: "Adney", email: "uadneyi@smh.com.au" },
      {
        firstName: "Aurilia",
        lastName: "Drewery",
        email: "adreweryj@pcworld.com",
      },
    ],
  },
];
const edinburghCourses = [
  {
    name: "Beginner Modern Dance",
    type: "modern",
    duration: "12 weeks",
    startDate: "01-04-2025",
    day: "Monday",
    startTime: "18:00",
    endTime: "20:00",
    description: "A ballet class for dancers at an beginner level",
    location: "Edinburgh",
    level: 1,
    price: 150.0,
    participants: [
      {
        firstName: "Mervin",
        lastName: "Croney",
        email: "mcroney0@tuttocitta.it",
      },
      {
        firstName: "Odille",
        lastName: "Lawdham",
        email: "olawdham1@blogs.com",
      },
      {
        firstName: "Gerianne",
        lastName: "Tipping",
        email: "gtipping2@mac.com",
      },
      { firstName: "Kenton", lastName: "Quelch", email: "kquelch3@census.gov" },
    ],
  },
  {
    name: "Intermediate Modern Dance",
    type: "modern",
    duration: "12 weeks",
    startDate: "02-04-2025",
    day: "Tuesday",
    startTime: "18:00",
    endTime: "20:00",
    description: "A ballet class for dancers at an intermediate level",
    location: "Edinburgh",
    level: 2,
    price: 150.0,
    participants: [
      {
        firstName: "Ruthe",
        lastName: "Britton",
        email: "rbritton4@ycombinator.com",
      },
      {
        firstName: "Edwina",
        lastName: "Hubbold",
        email: "ehubbold5@diigo.com",
      },
    ],
  },
  {
    name: "Advanced Modern Dance",
    type: "modern",
    duration: "12 weeks",
    startDate: "03-04-2025",
    day: "Wednesday",
    startTime: "18:00",
    endTime: "20:00",
    description: "A ballet class for dancers at an advanced level",
    location: "Edinburgh",
    level: 3,
    price: 150.0,
    participants: [
      {
        firstName: "Murdock",
        lastName: "Samsonsen",
        email: "msamsonsen6@rakuten.co.jp",
      },
      {
        firstName: "Almeria",
        lastName: "Harrild",
        email: "aharrild7@marketwatch.com",
      },
      { firstName: "Camile", lastName: "Drewitt", email: "cdrewitt8@icio.us" },
    ],
  },
  {
    name: "Beginner Tap Dancing",
    type: "tap",
    duration: "12 weeks",
    startDate: "05-04-2025",
    day: "Saturday",
    startTime: "12:00",
    endTime: "14:00",
    description: "A ballet class for dancers at an beginner level",
    level: 1,
    location: "Edinburgh",
    price: 125.0,
    participants: [
      {
        firstName: "Stephine",
        lastName: "Raittie",
        email: "sraittie9@sciencedirect.com",
      },
      {
        firstName: "Roxanna",
        lastName: "MacTrustie",
        email: "rmactrustiea@prnewswire.com",
      },
      {
        firstName: "Camile",
        lastName: "Allicock",
        email: "callicockb@house.gov",
      },
      {
        firstName: "Sholom",
        lastName: "Silber",
        email: "ssilberc@twitpic.com",
      },
      {
        firstName: "Wilhelm",
        lastName: "Brainsby",
        email: "wbrainsbyd@wufoo.com",
      },
      { firstName: "Kelwin", lastName: "Dollin", email: "kdolline@mysql.com" },
    ],
  },
  {
    name: "Intermediate Tap Dancing",
    type: "tap",
    duration: "12 weeks",
    startDate: "02-04-2025",
    day: "Tuesday",
    startTime: "18:00",
    endTime: "20:00",
    description: "A tap dancing class for dancers at an intermediate level",
    location: "Edinburgh",
    level: 2,
    price: 150.0,
    participants: [
      { firstName: "Terence", lastName: "Fysh", email: "tfyshf@yahoo.com" },
      { firstName: "Jami", lastName: "Dollar", email: "jdollarg@sogou.com" },
    ],
  },
  {
    name: "Advanced Tap Dancing",
    type: "tap",
    duration: "12 weeks",
    startDate: "2025-04-03",
    day: "Wednesday",
    startTime: "18:00",
    endTime: "20:00",
    description: "A tap dancing class for dancers at an advanced level",
    location: "Edinburgh",
    level: 3,
    price: 150.0,
    participants: [
      { firstName: "Kiley", lastName: "Bonas", email: "kbonash@eepurl.com" },
      { firstName: "Ursa", lastName: "Adney", email: "uadneyi@smh.com.au" },
      {
        firstName: "Aurilia",
        lastName: "Drewery",
        email: "adreweryj@pcworld.com",
      },
    ],
  },
];

module.exports.mockCourses = [
  ...londonCourses,
  ...glasgowCourses,
  ...edinburghCourses,
];
